In [ ]:


import numpy as np
import pandas as pd
import difflib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:


movies_data = pd.read_csv("movies.csv")

In [ ]:


movies_data.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [ ]:


movies_data.shape

(4803, 24)

In [ ]:
# ==========================================
# DATASET DETAILS
# ==========================================

movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [ ]:


movies_data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:


selected_features = [
    'genres',
    'keywords',
    'tagline',
    'cast',
    'director'
]

print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']

In [ ]:


for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

In [ ]:


combined_features = (
    movies_data['genres'] + ' ' +
    movies_data['keywords'] + ' ' +
    movies_data['tagline'] + ' ' +
    movies_data['cast'] + ' ' +
    movies_data['director']
)

In [ ]:


print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [ ]:


vectorizer = TfidfVectorizer()

In [ ]:

feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:

print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 124266 stored elements and shape (4803, 17318)>
  Coords	Values
  (0, 201)	0.07860022416510505
  (0, 274)	0.09021200873707368
  (0, 5274)	0.11108562744414445
  (0, 13599)	0.1036413987316636
  (0, 5437)	0.1036413987316636
  (0, 3678)	0.21392179219912877
  (0, 3065)	0.22208377802661425
  (0, 5836)	0.1646750903586285
  (0, 14378)	0.33962752210959823
  (0, 16587)	0.12549432354918996
  (0, 3225)	0.24960162956997736
  (0, 14271)	0.21392179219912877
  (0, 4945)	0.24025852494110758
  (0, 15261)	0.07095833561276566
  (0, 16998)	0.1282126322850579
  (0, 11192)	0.09049319826481456
  (0, 11503)	0.27211310056983656
  (0, 13349)	0.15021264094167086
  (0, 17007)	0.23643326319898797
  (0, 17290)	0.20197912553916567
  (0, 13319)	0.2177470539412484
  (0, 14064)	0.20596090415084142
  (0, 16668)	0.19843263965100372
  (0, 14608)	0.15150672398763912
  (0, 8756)	0.22709015857011816
  :	:
  (4801, 403)	0.17727585190343229
  (4801, 4835)	0.24713765026964
  (4801, 17266)	0.28860981849329476
  (4801, 13835)	0.27870029291200094
  (4801, 13175)	0.28860981849329476
  (4801, 17150)	0.3025765103586468
  (4801, 3511)	0.3025765103586468
  (4801, 13948)	0.3025765103586468
  (4801, 7269)	0.3025765103586468
  (4802, 11161)	0.17867407682173203
  (4802, 4518)	0.16784466610624255
  (4802, 2129)	0.3099656128577656
  (4802, 4980)	0.16078053641367315
  (4802, 6155)	0.18056463596934083
  (4802, 3436)	0.21753405888348784
  (4802, 4528)	0.19504460807622875
  (4802, 1316)	0.1960747079005741
  (4802, 12989)	0.1696476532191718
  (4802, 4371)	0.1538239182675544
  (4802, 6417)	0.21753405888348784
  (4802, 4608)	0.24002350969074696
  (4802, 2425)	0.24002350969074696
  (4802, 3654)	0.262512960498006
  (4802, 5367)	0.22969114490410403
  (4802, 6996)	0.5700048226105303

In [ ]:


similarity = cosine_similarity(feature_vectors)

In [ ]:

print(similarity)

[[1.         0.07219487 0.037733   ... 0.         0.         0.        ]
 [0.07219487 1.         0.03281499 ... 0.03575545 0.         0.        ]
 [0.037733   0.03281499 1.         ... 0.         0.05389661 0.        ]
 ...
 [0.         0.03575545 0.         ... 1.         0.         0.02651502]
 [0.         0.         0.05389661 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.02651502 0.         1.        ]]

In [26]:

movie_name = input('Enter your favourite movie name : ')

Enter your favourite movie name : sairat

In [27]:


list_of_all_titles = movies_data['title'].tolist()

print(list_of_all_titles[:20])

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies']

In [28]:


find_close_match = difflib.get_close_matches(
    movie_name,
    list_of_all_titles
)

print(find_close_match)

['Ararat', 'Valiant', 'Samsara']

In [29]:


close_match = find_close_match[0]

print(close_match)

Ararat

In [30]:


index_of_the_movie = movies_data[
    movies_data.title == close_match
]['index'].values[0]

print(index_of_the_movie)

2505

In [31]:


similarity_score = list(
    enumerate(similarity[index_of_the_movie])
)

print(similarity_score[:10])

[(0, np.float64(0.0255981990072777)), (1, np.float64(0.015286287031723737)), (2, np.float64(0.0)), (3, np.float64(0.02812403246397581)), (4, np.float64(0.0)), (5, np.float64(0.009071585221322023)), (6, np.float64(0.0)), (7, np.float64(0.0)), (8, np.float64(0.022921889258299775)), (9, np.float64(0.0))]

In [32]:


sorted_similar_movies = sorted(
    similarity_score,
    key=lambda x: x[1],
    reverse=True
)

print(sorted_similar_movies[:10])

[(2505, np.float64(1.0000000000000002)), (2637, np.float64(0.3718908225790207)), (1941, np.float64(0.16735238223860172)), (4199, np.float64(0.13493995194096423)), (4222, np.float64(0.13133152597286876)), (367, np.float64(0.12703598747019168)), (3627, np.float64(0.12325196812071054)), (4609, np.float64(0.12190753365674911)), (4661, np.float64(0.11782987186657254)), (2773, np.float64(0.11506698279004898))]

In [33]:


print("Movies Suggested For You :\n")

Movies Suggested For You :

In [34]:


i = 1

for movie in sorted_similar_movies:

    index = movie[0]

    title_from_index = movies_data[
        movies_data.index == index
    ]['title'].values[0]

    if i < 11:

        print(i, ".", title_from_index)

        i += 1

1 . Ararat
2 . Felicia's Journey
3 . Where the Truth Lies
4 . Yes
5 . Exotica
6 . The Interpreter
7 . The Sweet Hereafter
8 . When the Cat's Away
9 . The Big Parade
10 . Chloe

In [35]:


movie_name = input("Enter your favourite movie name : ")

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(
    movie_name,
    list_of_all_titles
)

close_match = find_close_match[0]

index_of_the_movie = movies_data[
    movies_data.title == close_match
]['index'].values[0]

similarity_score = list(
    enumerate(similarity[index_of_the_movie])
)

sorted_similar_movies = sorted(
    similarity_score,
    key=lambda x: x[1],
    reverse=True
)

print("\nMovies Suggested For You :\n")

i = 1

for movie in sorted_similar_movies:

    index = movie[0]

    title_from_index = movies_data[
        movies_data.index == index
    ]['title'].values[0]

    if i < 11:

        print(i, ".", title_from_index)

        i += 1

Enter your favourite movie name : sairat

Movies Suggested For You :

1 . Ararat
2 . Felicia's Journey
3 . Where the Truth Lies
4 . Yes
5 . Exotica
6 . The Interpreter
7 . The Sweet Hereafter
8 . When the Cat's Away
9 . The Big Parade
10 . Chloe

In [36]:


movies_data.shape

(4803, 24)

In [37]:


movies_data.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [38]:


movies_data.sample(10)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
2330,2330,17000000,Comedy,http://www.meangirls.com/,10625,female friendship high school fish out of wate...,en,Mean Girls,"Cady Heron is a hit with The Plastics, the A-l...",36.423717,...,97.0,"[{""iso_639_1"": ""sw"", ""name"": ""Kiswahili""}, {""i...",Released,Welcome to girl world.,Mean Girls,6.9,2320,Lindsay Lohan Rachel McAdams Tim Meadows Ana G...,"[{'name': 'Marci Liroff', 'gender': 1, 'depart...",Mark Waters
275,275,102000000,Action Thriller Science Fiction Mystery,NaN,180,self-fulfilling prophecy washington d.c. evide...,en,Minority Report,John Anderton is a top 'Precrime' cop in the l...,65.948959,...,145.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The system is perfect until it comes after you.,Minority Report,7.1,2608,Tom Cruise Colin Farrell Samantha Morton Max v...,"[{'name': 'John Williams', 'gender': 2, 'depar...",Steven Spielberg
1888,1888,23000000,Comedy Drama History,http://www.foxmovies.com/movies/eddie-the-eagle,319888,underdog olympic games ski jump biography sport,en,Eddie the Eagle,"Inspired by true events, Eddie the Eagle is a ...",29.365851,...,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"Win or lose, always aim high",Eddie the Eagle,7.2,661,Taron Egerton Hugh Jackman Christopher Walken ...,"[{'name': 'Matthew Vaughn', 'gender': 2, 'depa...",Dexter Fletcher
710,710,60000000,Comedy Drama Romance Fantasy,NaN,5994,workaholic second chance guardian angel christ...,en,The Family Man,"Jack's lavish, fast-paced lifestyle changes on...",19.705489,...,125.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What if you made different choices? What if yo...,The Family Man,6.5,521,Nicolas Cage T\u00e9a Leoni Don Cheadle Saul R...,"[{'name': 'Danny Elfman', 'gender': 2, 'depart...",Brett Ratner
2536,2536,15000000,Drama War,NaN,11778,vietnam veteran pennsylvania vietnam party escape,en,The Deer Hunter,A group of working-class friends decides to en...,19.786392,...,183.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,One of the most important and powerful films o...,The Deer Hunter,7.8,921,Robert De Niro John Cazale John Savage Christo...,"[{'name': 'Michael Deeley', 'gender': 2, 'depa...",Michael Cimino
2050,2050,25000000,Thriller Action Crime,http://www.thetransporterrefueled.com/,287948,transporter sequel suspense car bank heist,en,The Transporter Refueled,The fast-paced action movie is again set in th...,25.002715,...,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,He Delivers.,The Transporter Refueled,5.2,559,Ed Skrein Ray Stevenson Loan Chabanol Gabriell...,"[{'name': 'Luc Besson', 'gender': 2, 'departme...",Camille Delamarre
3859,3859,3440000,Crime Mystery Thriller,NaN,241766,wife husband relationship gangster mysterious ...,en,Lords of London,Tony is a notorious gangster with a big proble...,1.913302,...,90.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,"In this city, crime is a family business.",Lords of London,3.6,6,Glen Murphy Ray Winstone Giovanni Capalbo Sere...,"[{'name': 'Glen Murphy', 'gender': 2, 'departm...",Antonio Simoncini
2706,2706,14000000,Drama Romance,NaN,87729,france revolution biography president history,en,Jefferson in Paris,"His wife having recently died, Thomas Jefferso...",0.900442,...,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A powerful man torn between his love for one w...,Jefferson in Paris,5.2,10,Nick Nolte Greta Scacchi Thandie Newton Gwynet...,"[{'name': 'James Ivory', 'gender': 2, 'departm...",James Ivory
731,731,60000000,Action Thriller Adventure Crime,NaN,4824,fbi cold war hitman,en,The Jackal,Hired by a powerful member of the Russian mafi...,19.747459,...,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,How do you stop an assassin who has no identity?,The Jackal,6.1,527,Bruce Willis Richard Gere Sidney Poitier Diane...,"[{'name': 'Gary Levinsohn', 'gender': 2, 'depa...",Michael Caton-Jones
995,995,60000000,Fantasy Drama Romance,NaN,109491,civil war southern usa magic light dark,en,Beautiful Creatures,Ethan Wate just wants to get to know Lena Duch...,40.721373,...,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark secrets will come to light.,Beautiful Creatures,5.6,984,Alden Ehrenreich Alice Englert Jeremy Irons Vi...,"[{'name': 'David Valdes', 'gender': 2, 'depart...",Richard LaGravenese

In [39]:

movies_data.tail()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,,http://shanghaicalling.com/,126186,,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [40]:


print("Movie Recommendation System Executed Successfully")

Movie Recommendation System Executed Successfully